version: '3.8'
services:
    main:
        container_name: Serve
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000

    queue:
        container_name: Queue
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'

networks:
    laravel-exa:
        driver: bridge

volumes:
    db:
        driver: local
